source/main/default/objects/TriggerFactorySetting__mdt/TriggerFactorySetting__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Factory Setting</label>
    <pluralLabel>Trigger Factory Settings</pluralLabel>
</CustomObject>

source/main/default/objects/TriggerFactorySetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

source/main/default/objects/TriggerFactorySetting__mdt/fields/OrderOfExecution__c.field-meta.xml
<CustomField>
    <fullName>OrderOfExecution__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order of Execution</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/main/default/objects/TriggerFactorySetting__mdt/fields/SObjectName__c.field-meta.xml
<CustomField>
    <fullName>SObjectName__c</fullName>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

source/main/default/classes/TriggerMapping.cls
public without sharing class TriggerMapping {
    public static Map<String, List<String>> instance;

    /**
     * @description Single Design Pattern method for retrieval of Trigger Mappings
     * Retrieves Trigger Factory Settings and groups the Trigger Handlers to execute based on the Object name and their Order of Execution.
     * @author Dennis Grzyb
     * @return   the current instance of TriggerMapping
     */
    public static Map<String, List<String>> getInstance() {
        if (instance == null) {
            instance = new Map<String, List<String>>();
            for (TriggerFactorySetting__mdt setting : [
                SELECT SObjectName__c, ClassName__c
                FROM TriggerFactorySetting__mdt
                ORDER BY SObjectName__c, OrderOfExecution__c
            ]) {
                if (!instance.containsKey(setting.SObjectName__c.toUpperCase())) {
                    instance.put(setting.SObjectName__c.toUpperCase(), new List<String>());
                }
                instance.get(setting.SObjectName__c.toUpperCase()).add(setting.ClassName__c);
            }
        }
        return instance;
    }
}