source/main/default/objects/TriggerFactorySetting__mdt/TriggerFactorySetting__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Factory Setting</label>
    <pluralLabel>Trigger Factory Settings</pluralLabel>
</CustomObject>

source/main/default/objects/TriggerFactorySetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

source/main/default/objects/TriggerFactorySetting__mdt/fields/IsDisabled__c.field-meta.xml
<CustomField>
    <fullName>IsDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Disabled, the Trigger is skipped entirely in its execution, regardless of User and/or Profile</description>
    <label>Disabled</label>
    <type>Checkbox</type>
</CustomField>

source/main/default/objects/TriggerFactorySetting__mdt/fields/OrderOfExecution__c.field-meta.xml
<CustomField>
    <fullName>OrderOfExecution__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order of Execution</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

source/main/default/objects/TriggerFactorySetting__mdt/fields/RecordTypeIds__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeIds__c</fullName>
    <inlineHelpText>Leave this empty if the Trigger Handler should run for all Record Types of the SObject. Separate more than one Record Type Id by &quot;;&quot;</inlineHelpText>
    <label>Record Type Ids</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

source/main/default/objects/TriggerFactorySetting__mdt/fields/SObjectName__c.field-meta.xml
<CustomField>
    <fullName>SObjectName__c</fullName>
    <label>Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

source/main/default/classes/TriggerMappingTest.cls
@isTest
public with sharing class TriggerMappingTest {
    private static String factoryDummyValues = '[{"Label":"Account_Person","MasterLabel":"Account_Person","ClassName__c":"PersonAccountHandler","Language":"en_US","RecordTypeIds__c":"0121X000003twHvQAI","IsDisabled__c":false,"QualifiedApiName":"Account_Person","SObjectName__c":"Account","Id":"m005E0000002NLS","OrderOfExecution__c":1,"DeveloperName":"Account_Person","NamespacePrefix":null}]';
    @isTest
    static void getTriggerMap() {
        //Since we got rid of unmanaged metadata in our package, we are now verifying the existence of mapped Handlers by mocking an active Handler with a Record Type Filter.
        TriggerMapping.triggerFactorySettings = (List<TriggerFactorySetting__mdt>) JSON.deserialize(factoryDummyValues, List<TriggerFactorySetting__mdt>.class);

        TriggerMapping trigMap = TriggerMapping.getInstance();
        System.assert(trigMap.mappedHandlers.size() == 1);

        //DummyObject2 was previously part of the unmanaged metadata, but is auto-excluded here because it does not come up in a query where IsDisabled__c = false

        System.assert(!trigMap.mappedHandlers.containsKey('DUMMYOBJECT2'));

        System.assert(trigMap.recordTypeFilter.containsKey('PersonAccountHandler'));
    }

    @isTest
    static void getTriggerMapWhenTriggerFactorySettingsExist() {
        if ([SELECT COUNT() FROM TriggerFactorySetting__mdt] != 0) {
            TriggerMapping.getInstance();
        }
    }
}