source/main/default/objects/TriggerSettings__c/fields/DisableAllTriggers__c.field-meta.xml
<CustomField>
    <fullName>DisableAllTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disable all Triggers</label>
    <type>Checkbox</type>
</CustomField>

source/main/default/objects/TriggerSettings__c/fields/DisabledHandlers__c.field-meta.xml
<CustomField>
    <fullName>DisabledHandlers__c</fullName>
    <description>Used for temporary disabling of selective Trigger Handlers</description>
    <inlineHelpText>Separated with &quot;;&quot;</inlineHelpText>
    <label>Disabled Handlers</label>
    <type>TextArea</type>
</CustomField>

source/main/default/objects/TriggerSettings__c/fields/DisabledObjects__c.field-meta.xml
<CustomField>
    <fullName>DisabledObjects__c</fullName>
    <inlineHelpText>Please separate with &quot;;&quot;</inlineHelpText>
    <label>Disabled Objects</label>
    <type>TextArea</type>
</CustomField>

source/main/default/classes/TriggerSettingsTest.cls
@isTest
public with sharing class TriggerSettingsTest {
    /**
     * If there are no other Trigger Settings than the Dummys, the Dummy will be enough
     * To fill the gap between TriggerHandlerExtension and what can't be covered by it.
     */

    static final String OBJECT_NAME_TO_TEST = 'TriggerSettings__c';
    static final String CLASS_NAME_TO_TEST = 'DummyClassName';

    @isTest
    static void getInstanceTest() {
        TriggerSettings__c newSettingForUser = new TriggerSettings__c(SetupOwnerId = UserInfo.getUserId(), DisabledObjects__c = OBJECT_NAME_TO_TEST);
        insert newSettingForUser;
        TriggerSettings ts = TriggerSettings.getInstance();
        System.assert(ts.disabledObjects.size() > 0);
    }

    @isTest
    static void checkDisabledByObjectName() {
        TriggerSettings__c newSettingForUser = new TriggerSettings__c(SetupOwnerId = UserInfo.getUserId(), DisabledObjects__c = OBJECT_NAME_TO_TEST);
        insert newSettingForUser;
        TriggerSettings ts = TriggerSettings.getInstance();
        System.assert(ts.isDisabledBySObjectType(((SObject) Type.forName(OBJECT_NAME_TO_TEST).newInstance()).getSObjectType()));
    }

    @isTest
    static void checkGeneralBlock() {
        TriggerSettings__c newSettingForUser = new TriggerSettings__c(SetupOwnerId = UserInfo.getUserId(), DisableAllTriggers__c = true);
        insert newSettingForUser;
        System.assert(TriggerSettings.getInstance().isEveryThingDisabled);
    }

    @isTest
    static void checkDisabledByClassName() {
        TriggerSettings__c newSettingForUser = new TriggerSettings__c(SetupOwnerId = UserInfo.getUserId(), DisabledHandlers__c = CLASS_NAME_TO_TEST);
        insert newSettingForUser;
        System.assert(TriggerSettings.getInstance().isDisabledByClassName(CLASS_NAME_TO_TEST));
    }
}